name: fastai
channels:
- fastai
- pytorch
- defaults
dependencies:
- fastcore>=1.5.29
- torchvision>=0.11
- matplotlib
- pandas>=1.0.0
- requests
- pyyaml
- fastprogress>=0.2.4
- pillow>=9.0.0
- scikit-learn
- scipy
- spacy
- pytorch>=1.10.0
- fastdownload
